#!/bin/bash

set -e
set -o pipefail

cd $(cd "$(dirname $0)"; pwd)

rm -rf build
mkdir build
cd build
cmake .. -DPYTHON_BIN_PATH=$(which python3) -DPYTHON_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DASCEND_CI_BUILD_DIR=$(cd $(pwd)/../../../; pwd)
make -j8
